### ISSUE TITLE
`sender` slot is not always reset

### ISSUE THREAD

**Issue by MathisGD** [Vectorized/multicaller#7]
At line 89, the function `aggregateWithSender` can return early if the data is empty.

https://github.com/Vectorized/multicaller/blob/b53fdf32c24098a1e036471e7838efd131614810/src/Multicaller.sol#L88-L89

It happens after the writing in the storage of the sender.

https://github.com/Vectorized/multicaller/blob/b53fdf32c24098a1e036471e7838efd131614810/src/Multicaller.sol#L83-L84

So in this case the sender is not reset to `shl(160, 1)`. 

I would suggest to move the early return above the lines 83-84, or completely remove it.

NB: it saves some gas, because the 3 lines above are not executed then.

**Comment by Vectorized** [comment]
Many thanks. Will fix.
